#!/usr/bin/env python3
"""Generate the 24px caption icons for the Glass skin as LVGL 8 ALPHA_8BIT images.

LVGL 8's software renderer cannot scale 1-bit alpha bitmaps, so the classic
48/64px star, fan and thermometer cannot be reused at caption size. These are
drawn here at 24px with 8x supersampling and written to glass_icons.c. Pure
python, no dependencies; run from anywhere:

    python3 main/assets/gen_glass_icons.py
"""
import math
import os

SIZE = 24
SS = 8          # supersampling factor
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "glass_icons.c")


def point_in_polygon(x, y, poly):
    inside = False
    n = len(poly)
    j = n - 1
    for i in range(n):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if (yi > y) != (yj > y):
            xint = (xj - xi) * (y - yi) / (yj - yi) + xi
            if x < xint:
                inside = not inside
        j = i
    return inside


def rasterise(shape_fn):
    """shape_fn(x, y) -> bool for a point in icon pixel coordinates."""
    data = bytearray(SIZE * SIZE)
    for py in range(SIZE):
        for px in range(SIZE):
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    x = px + (sx + 0.5) / SS
                    y = py + (sy + 0.5) / SS
                    if shape_fn(x, y):
                        hits += 1
            data[py * SIZE + px] = round(255 * hits / (SS * SS))
    return data


def star_shape():
    cx, cy = 12.0, 12.6
    outer, inner = 11.0, 4.6
    pts = []
    for i in range(10):
        r = outer if i % 2 == 0 else inner
        a = -math.pi / 2 + i * math.pi / 5
        pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return lambda x, y: point_in_polygon(x, y, pts)


def fan_shape():
    cx, cy = 12.0, 12.0

    def inside(x, y):
        dx, dy = x - cx, y - cy
        d = math.hypot(dx, dy)
        # outer ring
        if 10.2 <= d <= 11.8:
            return True
        # hub
        if d <= 2.2:
            return True
        # three blades: teardrops from the hub outward
        for k in range(3):
            a = math.radians(90 + 120 * k)
            ca, sa = math.cos(a), math.sin(a)
            u = dx * ca + dy * sa          # along blade
            v = -dx * sa + dy * ca         # across blade
            if 2.4 <= u <= 8.6:
                t = (u - 2.4) / 6.2
                half_w = 1.2 + 2.6 * math.sin(math.pi * min(1.0, t * 1.15))
                if abs(v - 1.6 * t) <= half_w:
                    return True
        return False

    return inside


def thermo_shape():
    def inside(x, y):
        # bulb
        if math.hypot(x - 12.0, y - 17.8) <= 4.6:
            return True
        # stem with rounded top
        if 9.6 <= x <= 14.4 and 4.4 <= y <= 17.8:
            return True
        if math.hypot(x - 12.0, y - 4.4) <= 2.4:
            return True
        return False

    return inside


ICONS = [
    ("glass_icon_star", star_shape()),
    ("glass_icon_fan", fan_shape()),
    ("glass_icon_thermo", thermo_shape()),
]


def main():
    lines = [
        "/* Generated by gen_glass_icons.py; do not edit by hand. 24px ALPHA_8BIT",
        " * caption icons for the Glass skin, recoloured at draw time. */",
        '#include "lvgl.h"',
        "",
    ]
    for name, fn in ICONS:
        data = rasterise(fn)
        lines.append("static const uint8_t %s_map[] = {" % name)
        for row in range(SIZE):
            chunk = data[row * SIZE:(row + 1) * SIZE]
            lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
        lines.append("};")
        lines.append("const lv_img_dsc_t %s = {" % name)
        lines.append("    .header.cf = LV_IMG_CF_ALPHA_8BIT,")
        lines.append("    .header.always_zero = 0,")
        lines.append("    .header.reserved = 0,")
        lines.append("    .header.w = %d," % SIZE)
        lines.append("    .header.h = %d," % SIZE)
        lines.append("    .data_size = %d," % (SIZE * SIZE))
        lines.append("    .data = %s_map," % name)
        lines.append("};")
        lines.append("")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(OUT)


if __name__ == "__main__":
    main()
