#ifndef GLASS_ICONS_H
#define GLASS_ICONS_H

#include "lvgl.h"

/* 24px ALPHA_8BIT caption icons for the Glass skin, generated by
 * gen_glass_icons.py. Recolour with lv_obj_set_style_img_recolor(). */
LV_IMG_DECLARE(glass_icon_star);
LV_IMG_DECLARE(glass_icon_fan);
LV_IMG_DECLARE(glass_icon_thermo);

#endif /* GLASS_ICONS_H */
